### ISSUE TITLE
Class names

### ISSUE THREAD

**Issue by martoio** [Saidin86/teacozy#4]
Best practice tip: Don't use ``camelCase`` for class/ID names. It is normal to use ``kebab-case`` for CSS. (example: ``featured-title``) 
https://github.com/Saidin86/teacozy/blob/1d664dcacb96be24282652f218c45bff8ef38317/index.html#L24

**Comment by Saidin86** [comment]
ah - makes sense.  Used to powershell coding which tends to be more camel case
